/*
 * This file is generated by jOOQ.
 */
package domain.tables.records;


import domain.tables.Chat;

import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRecord extends UpdatableRecordImpl<ChatRecord> implements Record1<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chat.chat_id</code>.
     */
    public void setChatId(@NotNull String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chat.chat_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 50)
    @NotNull
    public String getChatId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return Chat.CHAT.CHAT_ID;
    }

    @Override
    @NotNull
    public String component1() {
        return getChatId();
    }

    @Override
    @NotNull
    public String value1() {
        return getChatId();
    }

    @Override
    @NotNull
    public ChatRecord value1(@NotNull String value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatRecord values(@NotNull String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatRecord
     */
    public ChatRecord() {
        super(Chat.CHAT);
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    @ConstructorProperties({ "chatId" })
    public ChatRecord(@NotNull String chatId) {
        super(Chat.CHAT);

        setChatId(chatId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    public ChatRecord(domain.tables.pojos.Chat value) {
        super(Chat.CHAT);

        if (value != null) {
            setChatId(value.getChatId());
            resetChangedOnNotNull();
        }
    }
}
