/*
 * This file is generated by jOOQ.
 */
package domain.tables.records;


import domain.tables.Link;

import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record3<String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.link.link</code>.
     */
    public void setLink(@NotNull String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.link.link</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 200)
    @NotNull
    public String getLink() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.link.last_activity_time</code>.
     */
    public void setLastActivityTime(@NotNull LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.link.last_activity_time</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getLastActivityTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.link.last_check_time</code>.
     */
    public void setLastCheckTime(@Nullable LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.link.last_check_time</code>.
     */
    @Nullable
    public LocalDateTime getLastCheckTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return Link.LINK.LINK_;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field2() {
        return Link.LINK.LAST_ACTIVITY_TIME;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field3() {
        return Link.LINK.LAST_CHECK_TIME;
    }

    @Override
    @NotNull
    public String component1() {
        return getLink();
    }

    @Override
    @NotNull
    public LocalDateTime component2() {
        return getLastActivityTime();
    }

    @Override
    @Nullable
    public LocalDateTime component3() {
        return getLastCheckTime();
    }

    @Override
    @NotNull
    public String value1() {
        return getLink();
    }

    @Override
    @NotNull
    public LocalDateTime value2() {
        return getLastActivityTime();
    }

    @Override
    @Nullable
    public LocalDateTime value3() {
        return getLastCheckTime();
    }

    @Override
    @NotNull
    public LinkRecord value1(@NotNull String value) {
        setLink(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value2(@NotNull LocalDateTime value) {
        setLastActivityTime(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value3(@Nullable LocalDateTime value) {
        setLastCheckTime(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord values(@NotNull String value1, @NotNull LocalDateTime value2, @Nullable LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    @ConstructorProperties({ "link", "lastActivityTime", "lastCheckTime" })
    public LinkRecord(@NotNull String link, @NotNull LocalDateTime lastActivityTime, @Nullable LocalDateTime lastCheckTime) {
        super(Link.LINK);

        setLink(link);
        setLastActivityTime(lastActivityTime);
        setLastCheckTime(lastCheckTime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(domain.tables.pojos.Link value) {
        super(Link.LINK);

        if (value != null) {
            setLink(value.getLink());
            setLastActivityTime(value.getLastActivityTime());
            setLastCheckTime(value.getLastCheckTime());
            resetChangedOnNotNull();
        }
    }
}
