version: "1"

services:
  postgresql:
    container_name: postgresTinkoffProject
    image: postgres:15
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - backend
    ports:
      - "5432:5432"

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./src/main/resources:/liquibase/changelog
    networks:
      - backend

  rabbit-mq:
    image: rabbitmq:3-management
    volumes:
      - rabbit-mq:/data/rabbitMQ
    networks:
      - backend
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  backend:

volumes:
  postgres:
  rabbit-mq: