/*
 * This file is generated by jOOQ.
 */
package domain;


import domain.tables.Chat;
import domain.tables.ChatToLink;
import domain.tables.Link;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.chat</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>public.chat_to_link</code>.
     */
    public static final ChatToLink CHAT_TO_LINK = ChatToLink.CHAT_TO_LINK;

    /**
     * The table <code>public.link</code>.
     */
    public static final Link LINK = Link.LINK;
}
