/*
 * This file is generated by jOOQ.
 */
package domain.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatToLink implements Serializable {

    private static final long serialVersionUID = 1L;

    private String link;
    private String chatId;

    public ChatToLink() {}

    public ChatToLink(ChatToLink value) {
        this.link = value.link;
        this.chatId = value.chatId;
    }

    @ConstructorProperties({ "link", "chatId" })
    public ChatToLink(
        @NotNull String link,
        @NotNull String chatId
    ) {
        this.link = link;
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.chat_to_link.link</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 200)
    @NotNull
    public String getLink() {
        return this.link;
    }

    /**
     * Setter for <code>public.chat_to_link.link</code>.
     */
    public void setLink(@NotNull String link) {
        this.link = link;
    }

    /**
     * Getter for <code>public.chat_to_link.chat_id</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 50)
    @NotNull
    public String getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.chat_to_link.chat_id</code>.
     */
    public void setChatId(@NotNull String chatId) {
        this.chatId = chatId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChatToLink other = (ChatToLink) obj;
        if (this.link == null) {
            if (other.link != null)
                return false;
        }
        else if (!this.link.equals(other.link))
            return false;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.link == null) ? 0 : this.link.hashCode());
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatToLink (");

        sb.append(link);
        sb.append(", ").append(chatId);

        sb.append(")");
        return sb.toString();
    }
}
