name: Bot_CI

on:
  pull_request:
    paths:
      - "project/bot/**"
    branches:
      - 'hw1'
  push:
    paths:
      - "project/bot/**"
    branches:
      - 'hw1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout head
        uses: actions/checkout@hw1
        
      - name: build bot
        run: mvn package -pl bot -am -DskipTests

      - name: Build Docker bot container
        run: docker build -t pash7e7/tinkoffProjectBotImage .

      - name: Log in to Docker Hub
        uses: docker/login-action@hw1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@hw1
        with:
          images: pash7e7/tinkoffProjectBotImage

      - name: Push Docker image
        uses: docker/build-push-action@hw1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}