name: CheckStyle_CI

on:
  push:
    paths:
      - "project/**"
    branches:
      - 'hw1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout head
        uses: actions/checkout@v3

      - name: Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: maven

      - name: check style bot
        run: mvn -pl bot -am checkstyle:check

      - name: check style scrapper
        run: mvn -pl scrapper -am checkstyle:check
        
      - name: check style link-parser  
        run: mvn -pl link-parser -am checkstyle:check

      - name: check style scrapper-jooq
        run: mvn -pl scrapper-jooq -am checkstyle:check