name: Scrapper_CI

on:
  pull_request:
    paths:
      - "project/scrapper/**"
    branches:
      - 'hw1'
  push:
    paths:
      - "project/scrapper/**"
    branches:
      - 'hw1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout head
        uses: actions/checkout@v3

      - name: Set up a cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
          cache: maven
        
      - name: build scrapper
        run: mvn package -pl scrapper -am -DskipTests

      - name: Build Docker scrapper container
        run: docker build -t pash7e7/tinkoffProjectScrapperImage .

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: pash7e7/tinkoffProjectScrapperImage

      - name: Push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}