name: Scrapper_CI

on:
  pull_request:
    paths:
      - "project/scrapper/**"
    branches:
      - 'hw1'
  push:
    paths:
      - "project/scrapper/**"
    branches:
      - 'hw1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout head
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: generate classes
        working-directory: ./project/scrapper-jooq
        run: mvn test
        
      - name: install scrapper
        working-directory: ./project/scrapper
        run: mvn install package -DskipTests

      - name: build scrapper
        working-directory: ./project/scrapper
        run: mvn package -am -DskipTests -X

      - name: Build Docker scrapper container
        working-directory: ./project/scrapper
        run: docker build -t pash7e7/tinkoff-project-scrapper-image .

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: | 
            pash7e7/tinkoff-project-scrapper-image
            ghcr.io/${{ github.repository }}

      - name: Push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./project/scrapper/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
